BaseConfig: reachability_gp_isaaclab22.yaml

BasicSettings:
  UseAmp: true

JointTrainAgent:
  NumEnvs: 128
  BatchSize: 128
  BatchLength: 64
  ImagineBatchSize: 128
  ImagineContext: 16
  ImagineHorizon: 15
  TrainModelEverySteps: 512
  TrainAgentEverySteps: 512
  ModelUpdate: 2
  AgentUpdate: 2
  SaveEverySteps: 2000000

Env:
  MakeKwargs:
    num_envs: 128
    use_fabric: True

FDPIRegimeDreamer:
  Gp:
    UpdateSteps: 1
  Gd:
    UpdateSteps: 1
  DualUpdate:
    UpdateSteps: 1
  Performance:
    AllowTF32: true
    MatmulPrecision: "high"
    CudnnBenchmark: false
    LogEverySteps: 4096
    DetailedLogEverySteps: 8192
    TimingLogEverySteps: 8192
    CacheReplayStarts: true
