BaseConfig: reachability_gp_isaaclab22_4090_fast.yaml

Wandb:
  Name: "FDPI-reachability-gp-IsaacLab22-SurgicalRobot5-4090fast-wm-safety50"

FDPIRegimeDreamer:
  WorldModelSampling:
    EnableSafetyCriticalSampling: true
    UniformRatio: 0.50
    SafetyCriticalRatio: 0.50
    HighCostThreshold: 0.1
    BoundaryLow: 0.05
    BoundaryHigh: 0.4
